name: lidar_camera_calibration
channels:
  - defaults
  - anaconda
dependencies:
  - python=3.9
  - pip
  - pip:
      - -r requirements.txt

      # environment tools
      - black
      - isort
      - mypy
